apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-cm
data:
  EULA: "TRUE"
  TYPE: "PAPER"
  VERSION: 1.21.8
  MODE: "survival"
  DIFFICULTY: "hard"
  MOTD: "Powered by k8s!"
  MAX_PLAYERS: "10"
  ALLOW_FLIGHT: "TRUE"
  OVERRIDE_ICON: "TRUE"
