apiVersion: v1
kind: ConfigMap
metadata:
  name: shawarmacraft-cm
data:
  EULA: "TRUE"
  SERVER_NAME: "Shawarmacraft"
  TYPE: "PAPER"
  VERSION: "1.21.7"
  MAX_PLAYERS: "10"
  MODE: "survival"
  DIFFICULTY: "hard"
  MOTD: "shawarma, oh shawarma, oh shawrma, life's better with you"
  ALLOW_FLIGHT: "TRUE"
  OVERRIDE_ICON: "TRUE"
  SNOOPER_ENABLED: "FALSE"
  ENABLE_WHITELIST: "TRUE"
  WHITELIST: "KarmaReplicant,BenSoccer,Tilted_Terror,TheOne69420,GuyWithAHatGWAH,Dapper_Q"
  RCON_CMDS_STARTUP: |-
    op KarmaReplicant
    gamerule doInsomnia false
    gamerule doFireTick false
    gamerule playersSleepingPercentage 5
    gamerule spawnRadius 25
