apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-svc
  labels:
    app: minecraft-server
spec:
  type: NodePort
  ports:
    - port: 25565
      nodePort: 30001
      name: minecraft
    - port: 8080
      name: dynmap
    - port: 25575
      nodePort: 30002
      name: rcon
  selector:
    app: minecraft-server
