apiVersion: v1
kind: Service
metadata:
  name: memos-svc
  namespace: memos
  labels:
    app: memos
spec:
  selector:
    app: memos
  type: NodePort
  ports:
    - protocol: TCP
      port: 5230
      targetPort: 5230
